# 项目相关配置
cbf:
  # 名称
  name: CBF
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2025
  # 文件路径 示例（ Windows配置D:/CBF/uploadPath，Linux配置 /home/CBF/uploadPath）
  profile: D:/CBF/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  # 读取日志配置文件
  config: classpath:log4j2.xml
  level:
    # 默认整个项目的日志级别
    root: info
    # 如果你想细化项目日志级别,com.cbf下的日志级别是info
    # com.cbf: info

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: false
  # redis 配置
  redis:
    # 地址
    host: 123.249.98.26
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: ENC(pdfZssTBqtBU8I8E85z2Hg==)
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8

# MyBatis Plus 配置
mybatis-plus:
  # 搜索指定包别名
  type-aliases-package: com.cbf.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    # 驼峰
    map-underscore-to-camel-case: true
    # 后台打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# PageHelper分页插件
pagehelper:
  helperDialect: mysql           # 数据库方言，支持 mysql、oracle、mariadb、sqlite、postgresql 等
  reasonable: true               # 启用合理化分页（pageNum<=0时自动设置为1，pageSize<=0时默认pageSize）
  supportMethodsArguments: true  # 支持通过 Mapper 方法参数传入分页参数
  params: count=countSql         # 用于设置 count 查询的参数映射
  autoRuntimeDialect: false      # 启用自动识别方言（建议关闭以提高性能）

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30