# 项目相关配置
cbf:
  name: CBF                          # 项目名称
  version: 1.0.0                     # 项目版本
  copyrightYear: 2025               # 版权年份
  profile: D:/CBF/uploadPath        # 文件上传路径（Win/Linux分别配置）
  addressEnabled: false             # 是否开启获取IP地址
  captchaType: math                 # 验证码类型：math（计算题）或 char（字符验证）

# 开发环境配置
server:
  port: 8080                         # 服务端口
  servlet:
    context-path: /                 # 应用上下文路径
  tomcat:
    uri-encoding: UTF-8             # URI 编码方式
    accept-count: 1000              # 最大等待连接数
    threads:
      max: 800                      # 最大线程数
      min-spare: 100                # 最小空闲线程数

# 日志配置
logging:
  config: classpath:log4j2.xml      # 日志配置文件路径
  level:
    root: info                      # 默认日志级别
    # com.cbf: info                 # 可选：细化日志级别

# 用户配置
user:
  password:
    maxRetryCount: 5                # 最大错误尝试次数
    lockTime: 10                    # 锁定时长（分钟）

# Spring 配置
spring:
  messages:
    basename: i18n/messages         # 国际化资源文件路径
  profiles:
    active: druid                   # 激活的配置环境
  servlet:
    multipart:
      max-file-size: 10MB           # 单个文件最大上传大小
      max-request-size: 20MB        # 请求总上传大小限制

  redis:
    host: 123.249.98.26             # Redis 主机地址
    port: 6379                      # Redis 端口
    database: 0                     # Redis 数据库索引
    password: ENC(pdfZssTBqtBU8I8E85z2Hg==)   # Redis 密码（加密）
    timeout: 10s                    # Redis 连接超时时间
    lettuce:
      pool:
        min-idle: 0                 # 最小空闲连接数
        max-idle: 8                 # 最大空闲连接数
        max-active: 8               # 最大活跃连接数

# MyBatis Plus 配置
mybatis-plus:
  type-aliases-package: com.cbf.**.domain              # 实体类包路径
  mapper-locations: classpath*:mapper/**/*Mapper.xml   # Mapper XML 路径
  configuration:
    map-underscore-to-camel-case: true                 # 开启驼峰命名转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 使用控制台输出 SQL 日志


# PageHelper分页插件
pagehelper:
  helperDialect: mysql           # 数据库方言，支持 mysql、oracle、mariadb、sqlite、postgresql 等
  reasonable: true               # 启用合理化分页（pageNum<=0时自动设置为1，pageSize<=0时默认pageSize）
  supportMethodsArguments: true  # 支持通过 Mapper 方法参数传入分页参数
  params: count=countSql         # 用于设置 count 查询的参数映射
  autoRuntimeDialect: false      # 启用自动识别方言（建议关闭以提高性能）

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30